命令稿啟動於 2018年03月11日 下午 07:05:34
]0;~
[32muser@X302L [33m~[0m
$ whoami;pwd
user
/home/user
]0;~
[32muser@X302L [33m~[0m
$ git config-l
git: 'config-l' is not a git command. See 'git --help'.
]0;~
[32muser@X302L [33m~[0m
$ git cong[Kfig -l
]0;~
[32muser@X302L [33m~[0m
$ git clone https://github.com/E24063113/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;~
[32muser@X302L [33m~[0m
$ exit

命令稿已於 2018年03月11日 下午 07:09:27
 完成